[versions]
android-gradlePlugin = "9.0.0"
kotlin = "2.3.0"

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradlePlugin" }
android-kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
