[versions]
android-gradlePlugin = "8.13.1"
kotlin = "2.2.21"

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradlePlugin" }
android-kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
